apiVersion: v1
kind: Secret
metadata:
  name: menshun-secrets
  namespace: menshun-pam
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  DATABASE_PASSWORD: cGFtX3NlY3VyZV9wYXNzd29yZA==  # pam_secure_password
  SECRET_KEY: c3VwZXJfc2VjcmV0X2tleV9mb3JfcHJvZHVjdGlvbg==  # super_secret_key_for_production
  AZURE_CLIENT_SECRET: eW91cl9henVyZV9jbGllbnRfc2VjcmV0  # your_azure_client_secret
  REDIS_PASSWORD: cmVkaXNfc2VjdXJlX3Bhc3N3b3Jk  # redis_secure_password

---
apiVersion: v1
kind: Secret
metadata:
  name: azure-config
  namespace: menshun-pam
type: Opaque
data:
  AZURE_CLIENT_ID: eW91cl9henVyZV9jbGllbnRfaWQ=  # your_azure_client_id
  AZURE_TENANT_ID: eW91cl9henVyZV90ZW5hbnRfaWQ=  # your_azure_tenant_id